# Generated by Django 5.0.7 on 2024-08-05 16:30

import bank_account.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.PositiveIntegerField(db_index=True, validators=[bank_account.validators.validate_24_digits])),
                ('balance', models.PositiveBigIntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acounts', to='person.person')),
            ],
        ),
    ]
