# Generated by Django 5.0.7 on 2024-08-06 12:38

import bank_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='IBAN',
            field=models.CharField(db_index=True, validators=[bank_account.validators.validate_24_digits]),
        ),
    ]
