# Generated by Django 5.0.7 on 2024-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0007_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=25),
        ),
    ]
