# Generated by Django 5.0.7 on 2024-08-05 16:30

import person.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('national_code', models.PositiveIntegerField(db_index=True, validators=[person.validators.validate_ten_digits])),
            ],
        ),
    ]
