# Generated by Django 5.0.7 on 2024-08-05 16:35

import person.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.BigIntegerField(db_index=True, validators=[person.validators.validate_ten_digits]),
        ),
    ]
