# Generated by Django 5.0.7 on 2024-08-08 12:43

import person.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.PositiveBigIntegerField(validators=[person.validators.validate_ten_digits]),
        ),
    ]
