# Generated by Django 5.0.7 on 2024-08-29 21:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=63)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('expire_time', models.DateTimeField()),
                ('job_category', models.CharField(choices=[('marketing roles', 'marketing roles'), ('business development roles', 'business development roles'), ('design roles', 'design roles'), ('analytics roles', 'analytics roles'), ('administrative roles', 'administrative roles'), ('IT roles', 'IT roles'), ('finance roles', 'finance roles'), ('healthcare roles', 'healthcare roles'), ('education roles', 'education roles'), ('engineering roles', 'engineering roles')], default='marketing roles', max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('insurance', models.BooleanField(default=False)),
                ('working_time', models.PositiveBigIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('applicants', models.ManyToManyField(default=None, related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
